name: glasszikr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  share_plus: ^7.2.1
  liquid_glass_widgets: ^0.13.0
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/Click.mp3
    - assets/sounds/pop.mp3
    - assets/sounds/soft.mp3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#004D40" # Dark emerald color to match our liquid theme
  adaptive_icon_foreground: "assets/images/app_icon.png"
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#0B1021"
    theme_color: "#0EA5E9"
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 256
